### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by forough-foroughi** [icclab/cyclops-billing#1]
UDR and RC module were installed successfuly, but when I try to build billing I got this Erorr:
## Triggering the build for RC Service and creation of WAR file

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Default Project
[INFO]    task-segment: [clean, install]
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Cannot execute mojo: clean. It requires a project with an existing pom.xml, but the build is not using one.

Thanks.

**Comment by skovzhaw** [comment]
Our new version should resolve this issue, could you try again?
